#!/usr/bin/env bash

declare -x DST_GAMEPLAY_GAME_MODE
: "${DST_GAMEPLAY_GAME_MODE:="endless"}"

declare -x DST_GAMEPLAY_MAX_PLAYERS
: "${DST_GAMEPLAY_MAX_PLAYERS:="6"}"

declare -x DST_GAMEPLAY_PVP
: "${DST_GAMEPLAY_PVP:="false"}"

declare -x DST_GAMEPLAY_PAUSE_WHEN_EMPTY
: "${DST_GAMEPLAY_PAUSE_WHEN_EMPTY:="true"}"

declare -x DST_GAMEPLAY_VOTE_ENABLED
: "${DST_GAMEPLAY_VOTE_ENABLED:="true"}"

declare -x DST_NETWORK_LAN_ONLY_SERVER
: "${DST_NETWORK_LAN_ONLY_SERVER:="false"}"

declare -x DST_NETWORK_CLUSTER_INTENTION
: "${DST_NETWORK_CLUSTER_INTENTION:="cooperative"}"

declare -x DST_NETWORK_CLUSTER_DESCRIPTION
: "${DST_NETWORK_CLUSTER_DESCRIPTION:=""}"

declare -x DST_NETWORK_CLUSTER_NAME
: "${DST_NETWORK_CLUSTER_NAME:="Don't Starve Together"}"

declare -x DST_NETWORK_CLUSTER_PASSWORD
: "${DST_NETWORK_CLUSTER_PASSWORD:=""}"

declare -x DST_NETWORK_OFFLINE_CLUSTER
: "${DST_NETWORK_OFFLINE_CLUSTER:="false"}"

declare -x DST_NETWORK_CLUSTER_LANGUAGE
: "${DST_NETWORK_CLUSTER_LANGUAGE:="en"}"

declare -x DST_NETWORK_TICK_RATE
: "${DST_NETWORK_TICK_RATE:="15"}"

declare -x DST_NETWORK_WHITELIST_SLOTS
: "${DST_NETWORK_WHITELIST_SLOTS:="0"}"

declare -x DST_NETWORK_AUTOSAVER_ENABLED
: "${DST_NETWORK_AUTOSAVER_ENABLED:="true"}"

declare -x DST_SHARD_ENABLED
: "${DST_SHARD_ENABLED:="false"}"

declare -x DST_SHARD_BIND_IP
: "${DST_SHARD_BIND_IP:="0.0.0.0"}"

declare -x DST_SHARD_MASTER_IP
: "${DST_SHARD_MASTER_IP:="127.0.0.1"}"

declare -x DST_SHARD_MASTER_PORT
: "${DST_SHARD_MASTER_PORT:="10888"}"

declare -x DST_SHARD_CLUSTER_KEY
: "${DST_SHARD_CLUSTER_KEY:="default"}"

declare -x DST_STEAM_GROUP_ONLY
: "${DST_STEAM_GROUP_ONLY:="false"}"

declare -x DST_STEAM_GROUP_ID
: "${DST_STEAM_GROUP_ID:="0"}"

declare -x DST_STEAM_GROUP_ADMINS
: "${DST_STEAM_GROUP_ADMINS:="false"}"

declare -x DST_MISC_CONSOLE_ENABLED
: "${DST_MISC_CONSOLE_ENABLED:="true"}"
