#!/usr/bin/env bash

declare -x DST_NETWORK_SERVER_PORT
[[ -z "${DST_NETWORK_SERVER_PORT}" ]] && DST_NETWORK_SERVER_PORT="10999"

declare -x DST_SHARD_IS_MASTER
[[ -z "${DST_SHARD_IS_MASTER}" ]] && DST_SHARD_IS_MASTER="true"

declare -x DST_SHARD_ID
[[ -z "${DST_SHARD_ID}" ]] && DST_SHARD_ID=""

declare -x DST_ACCOUNT_ENCODE_USER_PATH
[[ -z "${DST_ACCOUNT_ENCODE_USER_PATH}" ]] && DST_ACCOUNT_ENCODE_USER_PATH="true"

declare -x DST_STEAM_MASTER_SERVER_PORT
[[ -z "${DST_STEAM_MASTER_SERVER_PORT}" ]] && DST_STEAM_MASTER_SERVER_PORT="27017"

declare -x DST_STEAM_AUTHENTICATION_PORT
[[ -z "${DST_STEAM_AUTHENTICATION_PORT}" ]] && DST_STEAM_AUTHENTICATION_PORT="8767"
