#!/usr/bin/env bash

declare -x DST_OVERRIDE_BACKGROUND_NODE_RANGE
: "${DST_OVERRIDE_BACKGROUND_NODE_RANGE:=""}"

declare -x DST_OVERRIDE_DESC
: "${DST_OVERRIDE_DESC:=""}"

declare -x DST_OVERRIDE_HIDEMINIMAP
: "${DST_OVERRIDE_HIDEMINIMAP:="false"}"

declare -x DST_OVERRIDE_ID
: "${DST_OVERRIDE_ID:=""}"

declare -x DST_OVERRIDE_LOCATION
: "${DST_OVERRIDE_LOCATION:=""}"

declare -x DST_OVERRIDE_MAX_PLAYER_POSITION
: "${DST_OVERRIDE_MAX_PLAYER_POSITION:="999"}"

declare -x DST_OVERRIDE_MIN_PLAYER_POSITION
: "${DST_OVERRIDE_MIN_PLAYER_POSITION:="0"}"

declare -x DST_OVERRIDE_NAME
: "${DST_OVERRIDE_NAME:=""}"

declare -x DST_OVERRIDE_NUMRANDOM_SET_PIECES
: "${DST_OVERRIDE_NUMRANDOM_SET_PIECES:=""}"

declare -x DST_OVERRIDE_LEVEL_STRING
: "${DST_OVERRIDE_LEVEL_STRING:="false"}"

declare -x DST_OVERRIDE_ALTERNATEHUNT
: "${DST_OVERRIDE_ALTERNATEHUNT:=""}"

declare -x DST_OVERRIDE_ANGRYBEES
: "${DST_OVERRIDE_ANGRYBEES:=""}"

declare -x DST_OVERRIDE_ANTLIONTRIBUTE
: "${DST_OVERRIDE_ANTLIONTRIBUTE:=""}"

declare -x DST_OVERRIDE_AUTUMN
: "${DST_OVERRIDE_AUTUMN:=""}"

declare -x DST_OVERRIDE_BANANA
: "${DST_OVERRIDE_BANANA:=""}"

declare -x DST_OVERRIDE_BATS
: "${DST_OVERRIDE_BATS:=""}"

declare -x DST_OVERRIDE_BEARGER
: "${DST_OVERRIDE_BEARGER:=""}"

declare -x DST_OVERRIDE_BEEFALO
: "${DST_OVERRIDE_BEEFALO:=""}"

declare -x DST_OVERRIDE_BEEFALOHEAT
: "${DST_OVERRIDE_BEEFALOHEAT:=""}"

declare -x DST_OVERRIDE_BEES
: "${DST_OVERRIDE_BEES:=""}"

declare -x DST_OVERRIDE_BERRYBUSH
: "${DST_OVERRIDE_BERRYBUSH:=""}"

declare -x DST_OVERRIDE_BIRDS
: "${DST_OVERRIDE_BIRDS:=""}"

declare -x DST_OVERRIDE_BOONS
: "${DST_OVERRIDE_BOONS:=""}"

declare -x DST_OVERRIDE_BRANCHING
: "${DST_OVERRIDE_BRANCHING:=""}"

declare -x DST_OVERRIDE_BUNNYMEN
: "${DST_OVERRIDE_BUNNYMEN:=""}"

declare -x DST_OVERRIDE_BUTTERFLY
: "${DST_OVERRIDE_BUTTERFLY:=""}"

declare -x DST_OVERRIDE_BUZZARD
: "${DST_OVERRIDE_BUZZARD:=""}"

declare -x DST_OVERRIDE_CACTUS
: "${DST_OVERRIDE_CACTUS:=""}"

declare -x DST_OVERRIDE_CARROT
: "${DST_OVERRIDE_CARROT:=""}"

declare -x DST_OVERRIDE_CATCOON
: "${DST_OVERRIDE_CATCOON:=""}"

declare -x DST_OVERRIDE_CAVELIGHT
: "${DST_OVERRIDE_CAVELIGHT:=""}"

declare -x DST_OVERRIDE_CAVE_PONDS
: "${DST_OVERRIDE_CAVE_PONDS:=""}"

declare -x DST_OVERRIDE_CAVE_SPIDERS
: "${DST_OVERRIDE_CAVE_SPIDERS:=""}"

declare -x DST_OVERRIDE_CHESS
: "${DST_OVERRIDE_CHESS:=""}"

declare -x DST_OVERRIDE_DAY
: "${DST_OVERRIDE_DAY:=""}"

declare -x DST_OVERRIDE_DECIDUOUSMONSTER
: "${DST_OVERRIDE_DECIDUOUSMONSTER:=""}"

declare -x DST_OVERRIDE_DEERCLOPS
: "${DST_OVERRIDE_DEERCLOPS:=""}"

declare -x DST_OVERRIDE_DISEASE_DELAY
: "${DST_OVERRIDE_DISEASE_DELAY:=""}"

declare -x DST_OVERRIDE_DRAGONFLY
: "${DST_OVERRIDE_DRAGONFLY:=""}"

declare -x DST_OVERRIDE_EARTHQUAKES
: "${DST_OVERRIDE_EARTHQUAKES:=""}"

declare -x DST_OVERRIDE_FERN
: "${DST_OVERRIDE_FERN:=""}"

declare -x DST_OVERRIDE_FISSURE
: "${DST_OVERRIDE_FISSURE:=""}"

declare -x DST_OVERRIDE_FLINT
: "${DST_OVERRIDE_FLINT:=""}"

declare -x DST_OVERRIDE_FLOWER_CAVE
: "${DST_OVERRIDE_FLOWER_CAVE:=""}"

declare -x DST_OVERRIDE_FROGRAIN
: "${DST_OVERRIDE_FROGRAIN:=""}"

declare -x DST_OVERRIDE_GOOSEMOOSE
: "${DST_OVERRIDE_GOOSEMOOSE:=""}"

declare -x DST_OVERRIDE_GRASS
: "${DST_OVERRIDE_GRASS:=""}"

declare -x DST_OVERRIDE_HAS_OCEAN
: "${DST_OVERRIDE_HAS_OCEAN:=""}"

declare -x DST_OVERRIDE_HOUNDMOUND
: "${DST_OVERRIDE_HOUNDMOUND:=""}"

declare -x DST_OVERRIDE_HOUNDS
: "${DST_OVERRIDE_HOUNDS:=""}"

declare -x DST_OVERRIDE_HUNT
: "${DST_OVERRIDE_HUNT:=""}"

declare -x DST_OVERRIDE_KEEP_DISCONNECTED_TILES
: "${DST_OVERRIDE_KEEP_DISCONNECTED_TILES:=""}"

declare -x DST_OVERRIDE_KRAMPUS
: "${DST_OVERRIDE_KRAMPUS:=""}"

declare -x DST_OVERRIDE_LAYOUT_MODE
: "${DST_OVERRIDE_LAYOUT_MODE:=""}"

declare -x DST_OVERRIDE_LICHEN
: "${DST_OVERRIDE_LICHEN:=""}"

declare -x DST_OVERRIDE_LIEFS
: "${DST_OVERRIDE_LIEFS:=""}"

declare -x DST_OVERRIDE_LIGHTNING
: "${DST_OVERRIDE_LIGHTNING:=""}"

declare -x DST_OVERRIDE_LIGHTNINGGOAT
: "${DST_OVERRIDE_LIGHTNINGGOAT:=""}"

declare -x DST_OVERRIDE_LOOP
: "${DST_OVERRIDE_LOOP:=""}"

declare -x DST_OVERRIDE_LUREPLANTS
: "${DST_OVERRIDE_LUREPLANTS:=""}"

declare -x DST_OVERRIDE_MARSHBUSH
: "${DST_OVERRIDE_MARSHBUSH:=""}"

declare -x DST_OVERRIDE_MERM
: "${DST_OVERRIDE_MERM:=""}"

declare -x DST_OVERRIDE_METEORSHOWERS
: "${DST_OVERRIDE_METEORSHOWERS:=""}"

declare -x DST_OVERRIDE_METEORSPAWNER
: "${DST_OVERRIDE_METEORSPAWNER:=""}"

declare -x DST_OVERRIDE_MOLES
: "${DST_OVERRIDE_MOLES:=""}"

declare -x DST_OVERRIDE_MONKEY
: "${DST_OVERRIDE_MONKEY:=""}"

declare -x DST_OVERRIDE_MUSHROOM
: "${DST_OVERRIDE_MUSHROOM:=""}"

declare -x DST_OVERRIDE_MUSHTREE
: "${DST_OVERRIDE_MUSHTREE:=""}"

declare -x DST_OVERRIDE_NO_JOINING_ISLANDS
: "${DST_OVERRIDE_NO_JOINING_ISLANDS:=""}"

declare -x DST_OVERRIDE_NO_WORMHOLES_TO_DISCONNECTED_TILES
: "${DST_OVERRIDE_NO_WORMHOLES_TO_DISCONNECTED_TILES:=""}"

declare -x DST_OVERRIDE_PENGUINS
: "${DST_OVERRIDE_PENGUINS:=""}"

declare -x DST_OVERRIDE_PERD
: "${DST_OVERRIDE_PERD:=""}"

declare -x DST_OVERRIDE_PETRIFICATION
: "${DST_OVERRIDE_PETRIFICATION:=""}"

declare -x DST_OVERRIDE_PIGS
: "${DST_OVERRIDE_PIGS:=""}"

declare -x DST_OVERRIDE_PONDS
: "${DST_OVERRIDE_PONDS:=""}"

declare -x DST_OVERRIDE_PREFABSWAPS_START
: "${DST_OVERRIDE_PREFABSWAPS_START:=""}"

declare -x DST_OVERRIDE_RABBITS
: "${DST_OVERRIDE_RABBITS:=""}"

declare -x DST_OVERRIDE_REEDS
: "${DST_OVERRIDE_REEDS:=""}"

declare -x DST_OVERRIDE_REGROWTH
: "${DST_OVERRIDE_REGROWTH:=""}"

declare -x DST_OVERRIDE_ROADS
: "${DST_OVERRIDE_ROADS:=""}"

declare -x DST_OVERRIDE_ROCK
: "${DST_OVERRIDE_ROCK:=""}"

declare -x DST_OVERRIDE_ROCKY
: "${DST_OVERRIDE_ROCKY:=""}"

declare -x DST_OVERRIDE_ROCK_ICE
: "${DST_OVERRIDE_ROCK_ICE:=""}"

declare -x DST_OVERRIDE_SAPLING
: "${DST_OVERRIDE_SAPLING:=""}"

declare -x DST_OVERRIDE_SEASON_START
: "${DST_OVERRIDE_SEASON_START:=""}"

declare -x DST_OVERRIDE_SLURPER
: "${DST_OVERRIDE_SLURPER:=""}"

declare -x DST_OVERRIDE_SLURTLES
: "${DST_OVERRIDE_SLURTLES:=""}"

declare -x DST_OVERRIDE_SPECIALEVENT
: "${DST_OVERRIDE_SPECIALEVENT:=""}"

declare -x DST_OVERRIDE_SPIDERS
: "${DST_OVERRIDE_SPIDERS:=""}"

declare -x DST_OVERRIDE_SPRING
: "${DST_OVERRIDE_SPRING:=""}"

declare -x DST_OVERRIDE_START_LOCATION
: "${DST_OVERRIDE_START_LOCATION:=""}"

declare -x DST_OVERRIDE_SUMMER
: "${DST_OVERRIDE_SUMMER:=""}"

declare -x DST_OVERRIDE_TALLBIRDS
: "${DST_OVERRIDE_TALLBIRDS:=""}"

declare -x DST_OVERRIDE_TASK_SET
: "${DST_OVERRIDE_TASK_SET:=""}"

declare -x DST_OVERRIDE_TENTACLES
: "${DST_OVERRIDE_TENTACLES:=""}"

declare -x DST_OVERRIDE_TOUCHSTONE
: "${DST_OVERRIDE_TOUCHSTONE:=""}"

declare -x DST_OVERRIDE_TREES
: "${DST_OVERRIDE_TREES:=""}"

declare -x DST_OVERRIDE_TUMBLEWEED
: "${DST_OVERRIDE_TUMBLEWEED:=""}"

declare -x DST_OVERRIDE_WALRUS
: "${DST_OVERRIDE_WALRUS:=""}"

declare -x DST_OVERRIDE_WEATHER
: "${DST_OVERRIDE_WEATHER:=""}"

declare -x DST_OVERRIDE_WILDFIRES
: "${DST_OVERRIDE_WILDFIRES:=""}"

declare -x DST_OVERRIDE_WINTER
: "${DST_OVERRIDE_WINTER:=""}"

declare -x DST_OVERRIDE_WORLD_SIZE
: "${DST_OVERRIDE_WORLD_SIZE:=""}"

declare -x DST_OVERRIDE_WORMATTACKS
: "${DST_OVERRIDE_WORMATTACKS:=""}"

declare -x DST_OVERRIDE_WORMHOLE_PREFAB
: "${DST_OVERRIDE_WORMHOLE_PREFAB:=""}"

declare -x DST_OVERRIDE_WORMLIGHTS
: "${DST_OVERRIDE_WORMLIGHTS:=""}"

declare -x DST_OVERRIDE_WORMS
: "${DST_OVERRIDE_WORMS:=""}"

declare -x DST_OVERRIDE_RANDOM_SET_PIECES
: "${DST_OVERRIDE_RANDOM_SET_PIECES:=""}"

declare -x DST_OVERRIDE_REQUIRED_PREFABS
: "${DST_OVERRIDE_REQUIRED_PREFABS:="multiplayer_portal"}"

declare -x DST_OVERRIDE_REQUIRED_SETPIECES
: "${DST_OVERRIDE_REQUIRED_SETPIECES:=""}"

declare -x DST_OVERRIDE_SUBSTITUTES
: "${DST_OVERRIDE_SUBSTITUTES:=""}"

declare -x DST_OVERRIDE_VERSION
: "${DST_OVERRIDE_VERSION:="4"}"

declare -x DST_OVERRIDE_PRESET
: "${DST_OVERRIDE_PRESET:="${DST_SHARD_NAME}"}"

case "${DST_OVERRIDE_PRESET}" in
  "Master")
    DST_OVERRIDE_BACKGROUND_NODE_RANGE=${DST_OVERRIDE_BACKGROUND_NODE_RANGE:-}
    DST_OVERRIDE_DESC=${DST_OVERRIDE_DESC:-The standard Don\'t Starve experience.}
    DST_OVERRIDE_ID=${DST_OVERRIDE_ID:-SURVIVAL_TOGETHER}
    DST_OVERRIDE_LOCATION=${DST_OVERRIDE_LOCATION:-forest}
    DST_OVERRIDE_NAME=${DST_OVERRIDE_NAME:-Default}
    DST_OVERRIDE_NUMRANDOM_SET_PIECES=${DST_OVERRIDE_NUMRANDOM_SET_PIECES:-4}
    DST_OVERRIDE_RANDOM_SET_PIECES=${DST_OVERRIDE_RANDOM_SET_PIECES:-Sculptures_2,Sculptures_3,Sculptures_4,Sculptures_5,Chessy_1,Chessy_2,Chessy_3,Chessy_4,Chessy_5,Chessy_6,Maxwell1,Maxwell2,Maxwell3,Maxwell4,Maxwell6,Maxwell7,Warzone_1,Warzone_2,Warzone_3}
    DST_OVERRIDE_REQUIRED_SETPIECES=${DST_OVERRIDE_REQUIRED_SETPIECES:-Sculptures_1,Maxwell5}

    DST_OVERRIDE_ALTERNATEHUNT=${DST_OVERRIDE_ALTERNATEHUNT:-default}
    DST_OVERRIDE_ANGRYBEES=${DST_OVERRIDE_ANGRYBEES:-default}
    DST_OVERRIDE_ANTLIONTRIBUTE=${DST_OVERRIDE_ANTLIONTRIBUTE:-default}
    DST_OVERRIDE_AUTUMN=${DST_OVERRIDE_AUTUMN:-default}
    DST_OVERRIDE_BEARGER=${DST_OVERRIDE_BEARGER:-default}
    DST_OVERRIDE_BEEFALO=${DST_OVERRIDE_BEEFALO:-default}
    DST_OVERRIDE_BEEFALOHEAT=${DST_OVERRIDE_BEEFALOHEAT:-default}
    DST_OVERRIDE_BEES=${DST_OVERRIDE_BEES:-default}
    DST_OVERRIDE_BERRYBUSH=${DST_OVERRIDE_BERRYBUSH:-default}
    DST_OVERRIDE_BIRDS=${DST_OVERRIDE_BIRDS:-default}
    DST_OVERRIDE_BOONS=${DST_OVERRIDE_BOONS:-default}
    DST_OVERRIDE_BRANCHING=${DST_OVERRIDE_BRANCHING:-default}
    DST_OVERRIDE_BUTTERFLY=${DST_OVERRIDE_BUTTERFLY:-default}
    DST_OVERRIDE_BUZZARD=${DST_OVERRIDE_BUZZARD:-default}
    DST_OVERRIDE_CACTUS=${DST_OVERRIDE_CACTUS:-default}
    DST_OVERRIDE_CARROT=${DST_OVERRIDE_CARROT:-default}
    DST_OVERRIDE_CATCOON=${DST_OVERRIDE_CATCOON:-default}
    DST_OVERRIDE_CHESS=${DST_OVERRIDE_CHESS:-default}
    DST_OVERRIDE_DAY=${DST_OVERRIDE_DAY:-default}
    DST_OVERRIDE_DECIDUOUSMONSTER=${DST_OVERRIDE_DECIDUOUSMONSTER:-default}
    DST_OVERRIDE_DEERCLOPS=${DST_OVERRIDE_DEERCLOPS:-default}
    DST_OVERRIDE_DISEASE_DELAY=${DST_OVERRIDE_DISEASE_DELAY:-default}
    DST_OVERRIDE_DRAGONFLY=${DST_OVERRIDE_DRAGONFLY:-default}
    DST_OVERRIDE_FLINT=${DST_OVERRIDE_FLINT:-default}
    DST_OVERRIDE_FROGRAIN=${DST_OVERRIDE_FROGRAIN:-default}
    DST_OVERRIDE_GOOSEMOOSE=${DST_OVERRIDE_GOOSEMOOSE:-default}
    DST_OVERRIDE_GRASS=${DST_OVERRIDE_GRASS:-default}
    DST_OVERRIDE_HAS_OCEAN=${DST_OVERRIDE_HAS_OCEAN:-true}
    DST_OVERRIDE_HOUNDMOUND=${DST_OVERRIDE_HOUNDMOUND:-default}
    DST_OVERRIDE_HOUNDS=${DST_OVERRIDE_HOUNDS:-default}
    DST_OVERRIDE_HUNT=${DST_OVERRIDE_HUNT:-default}
    DST_OVERRIDE_KEEP_DISCONNECTED_TILES=${DST_OVERRIDE_KEEP_DISCONNECTED_TILES:-true}
    DST_OVERRIDE_KRAMPUS=${DST_OVERRIDE_KRAMPUS:-default}
    DST_OVERRIDE_LAYOUT_MODE=${DST_OVERRIDE_LAYOUT_MODE:-LinkNodesByKeys}
    DST_OVERRIDE_LIEFS=${DST_OVERRIDE_LIEFS:-default}
    DST_OVERRIDE_LIGHTNING=${DST_OVERRIDE_LIGHTNING:-default}
    DST_OVERRIDE_LIGHTNINGGOAT=${DST_OVERRIDE_LIGHTNINGGOAT:-default}
    DST_OVERRIDE_LOOP=${DST_OVERRIDE_LOOP:-default}
    DST_OVERRIDE_LUREPLANTS=${DST_OVERRIDE_LUREPLANTS:-default}
    DST_OVERRIDE_MARSHBUSH=${DST_OVERRIDE_MARSHBUSH:-default}
    DST_OVERRIDE_MERM=${DST_OVERRIDE_MERM:-default}
    DST_OVERRIDE_METEORSHOWERS=${DST_OVERRIDE_METEORSHOWERS:-default}
    DST_OVERRIDE_METEORSPAWNER=${DST_OVERRIDE_METEORSPAWNER:-default}
    DST_OVERRIDE_MOLES=${DST_OVERRIDE_MOLES:-default}
    DST_OVERRIDE_MUSHROOM=${DST_OVERRIDE_MUSHROOM:-default}
    DST_OVERRIDE_NO_JOINING_ISLANDS=${DST_OVERRIDE_NO_JOINING_ISLANDS:-true}
    DST_OVERRIDE_NO_WORMHOLES_TO_DISCONNECTED_TILES=${DST_OVERRIDE_NO_WORMHOLES_TO_DISCONNECTED_TILES:-true}
    DST_OVERRIDE_PENGUINS=${DST_OVERRIDE_PENGUINS:-default}
    DST_OVERRIDE_PERD=${DST_OVERRIDE_PERD:-default}
    DST_OVERRIDE_PETRIFICATION=${DST_OVERRIDE_PETRIFICATION:-default}
    DST_OVERRIDE_PIGS=${DST_OVERRIDE_PIGS:-default}
    DST_OVERRIDE_PONDS=${DST_OVERRIDE_PONDS:-default}
    DST_OVERRIDE_PREFABSWAPS_START=${DST_OVERRIDE_PREFABSWAPS_START:-default}
    DST_OVERRIDE_RABBITS=${DST_OVERRIDE_RABBITS:-default}
    DST_OVERRIDE_REEDS=${DST_OVERRIDE_REEDS:-default}
    DST_OVERRIDE_REGROWTH=${DST_OVERRIDE_REGROWTH:-default}
    DST_OVERRIDE_ROADS=${DST_OVERRIDE_ROADS:-default}
    DST_OVERRIDE_ROCK=${DST_OVERRIDE_ROCK:-default}
    DST_OVERRIDE_ROCK_ICE=${DST_OVERRIDE_ROCK_ICE:-default}
    DST_OVERRIDE_SAPLING=${DST_OVERRIDE_SAPLING:-default}
    DST_OVERRIDE_SEASON_START=${DST_OVERRIDE_SEASON_START:-default}
    DST_OVERRIDE_SPECIALEVENT=${DST_OVERRIDE_SPECIALEVENT:-default}
    DST_OVERRIDE_SPIDERS=${DST_OVERRIDE_SPIDERS:-default}
    DST_OVERRIDE_SPRING=${DST_OVERRIDE_SPRING:-default}
    DST_OVERRIDE_START_LOCATION=${DST_OVERRIDE_START_LOCATION:-default}
    DST_OVERRIDE_SUMMER=${DST_OVERRIDE_SUMMER:-default}
    DST_OVERRIDE_TALLBIRDS=${DST_OVERRIDE_TALLBIRDS:-default}
    DST_OVERRIDE_TASK_SET=${DST_OVERRIDE_TASK_SET:-default}
    DST_OVERRIDE_TENTACLES=${DST_OVERRIDE_TENTACLES:-default}
    DST_OVERRIDE_TOUCHSTONE=${DST_OVERRIDE_TOUCHSTONE:-default}
    DST_OVERRIDE_TREES=${DST_OVERRIDE_TREES:-default}
    DST_OVERRIDE_TUMBLEWEED=${DST_OVERRIDE_TUMBLEWEED:-default}
    DST_OVERRIDE_WALRUS=${DST_OVERRIDE_WALRUS:-default}
    DST_OVERRIDE_WEATHER=${DST_OVERRIDE_WEATHER:-default}
    DST_OVERRIDE_WILDFIRES=${DST_OVERRIDE_WILDFIRES:-default}
    DST_OVERRIDE_WINTER=${DST_OVERRIDE_WINTER:-default}
    DST_OVERRIDE_WORLD_SIZE=${DST_OVERRIDE_WORLD_SIZE:-default}
    DST_OVERRIDE_WORMHOLE_PREFAB=${DST_OVERRIDE_WORMHOLE_PREFAB:-wormhole}
    ;;

  "Caves")
    DST_OVERRIDE_BACKGROUND_NODE_RANGE=${DST_OVERRIDE_BACKGROUND_NODE_RANGE:-0,1}
    DST_OVERRIDE_DESC=${DST_OVERRIDE_DESC:-Delve into the caves... together!}
    DST_OVERRIDE_ID=${DST_OVERRIDE_ID:-DST_CAVE}
    DST_OVERRIDE_LOCATION=${DST_OVERRIDE_LOCATION:-cave}
    DST_OVERRIDE_NAME=${DST_OVERRIDE_NAME:-The Caves}
    DST_OVERRIDE_NUMRANDOM_SET_PIECES=${DST_OVERRIDE_NUMRANDOM_SET_PIECES:-0}
    DST_OVERRIDE_RANDOM_SET_PIECES=${DST_OVERRIDE_RANDOM_SET_PIECES:-}
    DST_OVERRIDE_REQUIRED_SETPIECES=${DST_OVERRIDE_REQUIRED_SETPIECES:-}

    DST_OVERRIDE_BANANA=${DST_OVERRIDE_BANANA:-default}
    DST_OVERRIDE_BATS=${DST_OVERRIDE_BATS:-default}
    DST_OVERRIDE_BERRYBUSH=${DST_OVERRIDE_BERRYBUSH:-default}
    DST_OVERRIDE_BOONS=${DST_OVERRIDE_BOONS:-default}
    DST_OVERRIDE_BRANCHING=${DST_OVERRIDE_BRANCHING:-default}
    DST_OVERRIDE_BUNNYMEN=${DST_OVERRIDE_BUNNYMEN:-default}
    DST_OVERRIDE_CAVE_PONDS=${DST_OVERRIDE_CAVE_PONDS:-default}
    DST_OVERRIDE_CAVE_SPIDERS=${DST_OVERRIDE_CAVE_SPIDERS:-default}
    DST_OVERRIDE_CAVELIGHT=${DST_OVERRIDE_CAVELIGHT:-default}
    DST_OVERRIDE_CHESS=${DST_OVERRIDE_CHESS:-default}
    DST_OVERRIDE_DISEASE_DELAY=${DST_OVERRIDE_DISEASE_DELAY:-default}
    DST_OVERRIDE_EARTHQUAKES=${DST_OVERRIDE_EARTHQUAKES:-default}
    DST_OVERRIDE_FERN=${DST_OVERRIDE_FERN:-default}
    DST_OVERRIDE_FISSURE=${DST_OVERRIDE_FISSURE:-default}
    DST_OVERRIDE_FLINT=${DST_OVERRIDE_FLINT:-default}
    DST_OVERRIDE_FLOWER_CAVE=${DST_OVERRIDE_FLOWER_CAVE:-default}
    DST_OVERRIDE_GRASS=${DST_OVERRIDE_GRASS:-default}
    DST_OVERRIDE_LAYOUT_MODE=${DST_OVERRIDE_LAYOUT_MODE:-RestrictNodesByKey}
    DST_OVERRIDE_LICHEN=${DST_OVERRIDE_LICHEN:-default}
    DST_OVERRIDE_LIEFS=${DST_OVERRIDE_LIEFS:-default}
    DST_OVERRIDE_LOOP=${DST_OVERRIDE_LOOP:-default}
    DST_OVERRIDE_MARSHBUSH=${DST_OVERRIDE_MARSHBUSH:-default}
    DST_OVERRIDE_MONKEY=${DST_OVERRIDE_MONKEY:-default}
    DST_OVERRIDE_MUSHROOM=${DST_OVERRIDE_MUSHROOM:-default}
    DST_OVERRIDE_MUSHTREE=${DST_OVERRIDE_MUSHTREE:-default}
    DST_OVERRIDE_PREFABSWAPS_START=${DST_OVERRIDE_PREFABSWAPS_START:-default}
    DST_OVERRIDE_REEDS=${DST_OVERRIDE_REEDS:-default}
    DST_OVERRIDE_REGROWTH=${DST_OVERRIDE_REGROWTH:-default}
    DST_OVERRIDE_ROADS=${DST_OVERRIDE_ROADS:-never}
    DST_OVERRIDE_ROCK=${DST_OVERRIDE_ROCK:-default}
    DST_OVERRIDE_ROCKY=${DST_OVERRIDE_ROCKY:-default}
    DST_OVERRIDE_SAPLING=${DST_OVERRIDE_SAPLING:-default}
    DST_OVERRIDE_SEASON_START=${DST_OVERRIDE_SEASON_START:-default}
    DST_OVERRIDE_SLURPER=${DST_OVERRIDE_SLURPER:-default}
    DST_OVERRIDE_SLURTLES=${DST_OVERRIDE_SLURTLES:-default}
    DST_OVERRIDE_START_LOCATION=${DST_OVERRIDE_START_LOCATION:-caves}
    DST_OVERRIDE_TASK_SET=${DST_OVERRIDE_TASK_SET:-cave_default}
    DST_OVERRIDE_TENTACLES=${DST_OVERRIDE_TENTACLES:-default}
    DST_OVERRIDE_TOUCHSTONE=${DST_OVERRIDE_TOUCHSTONE:-default}
    DST_OVERRIDE_TREES=${DST_OVERRIDE_TREES:-default}
    DST_OVERRIDE_WEATHER=${DST_OVERRIDE_WEATHER:-default}
    DST_OVERRIDE_WORLD_SIZE=${DST_OVERRIDE_WORLD_SIZE:-default}
    DST_OVERRIDE_WORMATTACKS=${DST_OVERRIDE_WORMATTACKS:-default}
    DST_OVERRIDE_WORMLIGHTS=${DST_OVERRIDE_WORMLIGHTS:-default}
    DST_OVERRIDE_WORMS=${DST_OVERRIDE_WORMS:-default}
    DST_OVERRIDE_WORMHOLE_PREFAB=${DST_OVERRIDE_WORMHOLE_PREFAB:-tentacle_pillar}
    ;;
esac
