#!/usr/bin/env bash

declare -x DST_MOD_OVERRIDES_RAW
[[ -z "${DST_MOD_OVERRIDES_RAW}" ]] && DST_MOD_OVERRIDES_RAW=""

declare -x DST_SERVER_MOD_SETUP
[[ -z "${DST_SERVER_MOD_SETUP}" ]] && DST_SERVER_MOD_SETUP=""

declare -x DST_SERVER_MOD_COLLECTION_SETUP
[[ -z "${DST_SERVER_MOD_COLLECTION_SETUP}" ]] && DST_SERVER_MOD_COLLECTION_SETUP=""

declare -x DST_FORCE_ENABLE_MODS
[[ -z "${DST_FORCE_ENABLE_MODS}" ]] && DST_FORCE_ENABLE_MODS=""

declare -x DST_ENABLE_MOD_ERROR
[[ -z "${DST_ENABLE_MOD_ERROR}" ]] && DST_ENABLE_MOD_ERROR="false"

declare -x DST_ENABLE_MOD_DEBUG_PRINT
[[ -z "${DST_ENABLE_MOD_DEBUG_PRINT}" ]] && DST_ENABLE_MOD_DEBUG_PRINT="false"
