#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname \*.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="./dontstarve_dedicated_server_nullrenderer -console"

[[ -n "${DST_SERVER_PERSISTENT_STORAGE_ROOT}" ]] && STARTCMD="${STARTCMD} -persistent_storage_root ${DST_SERVER_PERSISTENT_STORAGE_ROOT}"
[[ -n "${DST_SERVER_CONF_DIR}" ]] && STARTCMD="${STARTCMD} -conf_dir ${DST_SERVER_CONF_DIR}"
[[ -n "${DST_SERVER_REGION}" ]] && STARTCMD="${STARTCMD} -region ${DST_SERVER_REGION}"
[[ -n "${DST_SERVER_CLUSTER}" ]] && STARTCMD="${STARTCMD} -cluster ${DST_SERVER_CLUSTER}"
[[ -n "${DST_SHARD_NAME}" ]] && STARTCMD="${STARTCMD} -shard ${DST_SHARD_NAME}"

pushd /usr/share/game/bin >/dev/null
  echo "> starting game service"
  exec su-exec steam ${STARTCMD}
popd >/dev/null
