#!/bin/bash

checker() {
  if [[ $1 -eq 0 ]]
  then
    echo "ok"
  else
    echo "failed"
    /bin/s6-svscanctl -t /etc/s6
  fi
}

/usr/bin/steamcmd +runscript \
  /game/params.txt

if [[ -n "${DST_WORLDGEN_CONFIG}" && -f "${DST_WORLDGEN_CONFIG}" ]]
then
  echo -n "Copy worldgen overrides... "
  cp ${DST_WORLDGEN_CONFIG} \
    /game/DoNotStarveTogether/Cluster_1/Master/worldgenoverride.lua
  checker $?
else
  echo -n "Writing worldgen overrides... "
  /usr/bin/templater -d -p dst \
    -o /game/DoNotStarveTogether/Cluster_1/Master/worldgenoverride.lua \
    /game/DoNotStarveTogether/Cluster_1/Master/worldgenoverride.lua.tmpl
  checker $?
fi

echo -n "Writing Cluster ini... "
/usr/bin/templater -d -p dst \
  -o /game/DoNotStarveTogether/Cluster_1/cluster.ini \
  /game/DoNotStarveTogether/Cluster_1/cluster.ini.tmpl
checker $?

echo -n "Writing mod setup... "
/usr/bin/templater -d -p dst \
  -o /game/mods/dedicated_server_mods_setup.lua \
  /game/mods/dedicated_server_mods_setup.lua.tmpl
checker $?

echo -n "Writing mod settings... "
/usr/bin/templater -d -p dst \
  -o /game/mods/modsettings.lua \
  /game/mods/modsettings.lua.tmpl
checker $?

echo -n "Writing Cluster_Token..."
echo ${DST_CLUSTER_TOKEN} > /game/DoNotStarveTogether/Cluster_1/cluster_token.txt
checker $?