FROM ghcr.io/dockhippie/steamcmd:latest-amd64@sha256:aaf382fa9c2aa2bae35d8388c99ec9ad5bfa51157a0350037398d2585e38cb9f

VOLUME ["/var/lib/game", "/var/log/steam"]
EXPOSE 10999 27017 8767

WORKDIR /var/lib/game
CMD ["/usr/bin/container"]

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y libstdc++6:i386 libgcc1:i386 libcurl4-gnutls-dev:i386 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /usr/share/game && \
  chown -R steam:steam /usr/share/game && \
  /usr/bin/steamcmd +login anonymous +force_install_dir /usr/share/game +app_update 343050 validate +quit && \
  rm -rf /var/log/steam/*

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
