FROM ghcr.io/dockhippie/steamcmd:latest-amd64@sha256:33bec4f982b0a88386df09d9539a6f43253c53ed2a331440512b5895a37f0ec0

VOLUME ["/var/lib/game", "/var/log/steam"]
EXPOSE 10999 27017 8767

WORKDIR /var/lib/game
CMD ["/usr/bin/container"]

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y libstdc++6:i386 libgcc1:i386 libcurl4-gnutls-dev:i386 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /usr/share/game && \
	chown -R steam:steam /usr/share/game && \
	/usr/bin/steamcmd +login anonymous +force_install_dir /usr/share/game +app_update 343050 validate +quit && \
  rm -rf /var/log/steam/*

COPY ./overlay /
