#!/bin/bash

if [[ ! -f /game/server/save/adminlist.txt ]]
then
  touch /game/server/save/adminlist.txt
fi

if [[ ! -f /game/server/save/blocklist.txt ]]
then
  touch /game/server/save/blocklist.txt
fi

if [[ ! -f /game/server/save/whitelist.txt ]]
then
  touch /game/server/save/whitelist.txt
fi
